name: WiFiOffline
options:
  createIntermediateGroups: true
configs:
  Debug: debug
  Release: release

targets:
  WiFiOffline:
    type: application
    platform: iOS
    deploymentTarget: "14.0"
    # Trỏ trực tiếp tới file để tránh lỗi path folder
    sources:
      - path: ./Sources/WiFiOfflineApp.swift
      - path: ./Sources/ContentView.swift

    # Không ký khi build
    settings:
      CODE_SIGN_STYLE: Manual
      CODE_SIGNING_ALLOWED: NO
      CODE_SIGNING_REQUIRED: NO
      CODE_SIGNING_IDENTITY: ""

    # XcodeGen sẽ tự sinh Info.plist từ properties bên dưới
    info:
      properties:
        CFBundleName: WiFiOffline
        CFBundleIdentifier: com.example.wifioffline
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UIRequiredDeviceCapabilities:
          - arm64
