name: WiFiOffline
options:
  createIntermediateGroups: true
configs:
  Debug: debug
  Release: release
settings:
  CODE_SIGN_STYLE: Manual
  CODE_SIGNING_ALLOWED: NO
  CODE_SIGNING_REQUIRED: NO
  CODE_SIGNING_IDENTITY: ""
targets:
  WiFiOffline:
    type: application
    platform: iOS
    deploymentTarget: "14.0"
    sources:
      - path: Sources
    entitlements:
      path: Entitlements/WiFiOffline.entitlements
    info:
      properties:
        CFBundleName: WiFiOffline
        CFBundleIdentifier: com.example.wifioffline
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        UILaunchStoryboardName: ""
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UIRequiredDeviceCapabilities:
          - arm64
