name: WiFiOffline
options:
  createIntermediateGroups: true
configs:
  Debug: debug
  Release: release

targets:
  WiFiOffline:
    type: application
    platform: iOS
    deploymentTarget: "14.0"

    # Quét TẤT CẢ file Swift trong repo (tránh lỗi "path")
    sources:
      - path: .

    # Không ký khi build (unsigned)
    settings:
      CODE_SIGN_STYLE: Manual
      CODE_SIGNING_ALLOWED: NO
      CODE_SIGNING_REQUIRED: NO
      CODE_SIGNING_IDENTITY: ""

    info:
      properties:
        CFBundleName: WiFiOffline
        CFBundleIdentifier: com.example.wifioffline
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UIRequiredDeviceCapabilities:
          - arm64
