name: build-unsigned-ipa

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show repo tree
        run: |
          pwd
          echo "=== Root directory ==="
          ls -la
          echo "=== Sources directory ==="
          ls -la Sources/ || echo "Sources directory not found"
          echo "=== Entitlements directory ==="
          ls -la Entitlements/ || echo "Entitlements directory not found"
          echo "=== project.yml content ==="
          cat project.yml || echo "project.yml not found"

      - name: Install tools
        run: |
          brew update
          brew install xcodegen
          xcodebuild -version
          xcrun --sdk iphoneos --show-sdk-version

      - name: Generate Xcode project
        run: |
          xcodegen generate
          echo "Generated project files:"
          ls -la *.xcodeproj || echo "No .xcodeproj found"
          ls -la *.xcworkspace || echo "No .xcworkspace found"

      - name: Build unsigned .app (iphoneos)
        run: |
          set -euo pipefail
          
          # Tìm project file (.xcodeproj hoặc .xcworkspace)
          if [ -f "WiFiOffline.xcworkspace" ]; then
            PROJECT_FILE="WiFiOffline.xcworkspace"
            PROJECT_FLAG="-workspace"
          elif [ -f "WiFiOffline.xcodeproj" ]; then
            PROJECT_FILE="WiFiOffline.xcodeproj"
            PROJECT_FLAG="-project"
          else
            echo "Error: No .xcodeproj or .xcworkspace found"
            exit 1
          fi
          
          echo "Using project file: $PROJECT_FILE"
          
          xcodebuild $PROJECT_FLAG "$PROJECT_FILE" \
            -scheme "WiFiOffline" \
            -configuration Release \
            -sdk iphoneos \
            -destination 'generic/platform=iOS' \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_IDENTITY="" \
            PROVISIONING_PROFILE="" \
            DEVELOPMENT_TEAM="" \
            -derivedDataPath build \
            clean build

      - name: Package IPA
        run: |
          set -euo pipefail
          APP_PATH=$(find build -name "*.app" -type d -print -quit)
          if [ -z "$APP_PATH" ]; then
            echo "Error: No .app file found in build directory"
            echo "Contents of build directory:"
            find build -type f -name "*.app" || echo "No .app files found"
            find build -name "*WiFiOffline*" || echo "No WiFiOffline files found"
            ls -la build/
            exit 1
          fi
          echo "Found app at: $APP_PATH"
          mkdir -p Payload
          cp -R "$APP_PATH" Payload/
          /usr/bin/zip -qry WiFiOffline-unsigned.ipa Payload
          rm -rf Payload
          ls -la WiFiOffline-unsigned.ipa

      - name: Upload unsigned IPA
        uses: actions/upload-artifact@v4
        with:
          name: WiFiOffline-unsigned
          path: WiFiOffline-unsigned.ipa