- name: Build unsigned .app (iphoneos)
shell: bash
run: |
  set -euo pipefail

  echo "== Debug: liệt kê thư mục sau khi tuist generate =="
  pwd
  echo "---"
  ls -lah
  echo "---"
  find . -maxdepth 2 -type d -name "*.xcworkspace" -print
  find . -maxdepth 2 -type d -name "*.xcodeproj" -print
  echo "===================================================="

  DERIVED="build"
  SCHEME="WiFiOffline"

  # Bật nullglob để pattern *.xcworkspace không giữ nguyên chuỗi khi không khớp
  shopt -s nullglob

  # Tìm workspace/project ở thư mục hiện tại (gốc repo) — KHÔNG cd vào trong .xcworkspace
  workspaces=( ./*.xcworkspace )
  projects=( ./*.xcodeproj )

  # Ưu tiên workspace nếu có; nếu không thì dùng project
  if (( ${#workspaces[@]} > 0 )); then
    WS="${workspaces[0]}"
    echo "Found workspace: $WS"
    xcodebuild \
      -workspace "$WS" \
      -scheme "$SCHEME" \
      -configuration Release \
      -sdk iphoneos \
      -destination 'generic/platform=iOS' \
      CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGNING_IDENTITY="" \
      -derivedDataPath "$DERIVED" \
      clean build
  elif (( ${#projects[@]} > 0 )); then
    PROJ="${projects[0]}"
    echo "Found project: $PROJ"
    xcodebuild \
      -project "$PROJ" \
      -scheme "$SCHEME" \
      -configuration Release \
      -sdk iphoneos \
      -destination 'generic/platform=iOS' \
      CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGNING_IDENTITY="" \
      -derivedDataPath "$DERIVED" \
      clean build
  else
    echo "❌ Không tìm thấy *.xcworkspace hoặc *.xcodeproj ở thư mục hiện tại."
    exit 1
  fi
