name: build-unsigned-ipa

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install XcodeGen
        run: |
          brew update
          brew install xcodegen

      - name: Generate Xcode project
        run: xcodegen generate

      - name: Build (iphoneos, unsigned)
        run: |
          set -e
          xcodebuild -scheme "WiFiOffline" -configuration Release -sdk iphoneos -destination 'generic/platform=iOS' CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGNING_IDENTITY="" build | xcpretty || true
          APP_PATH=$(find build/Release-iphoneos -maxdepth 1 -name "*.app" -print -quit)
          if [ -z "$APP_PATH" ]; then
            # fallback to default DerivedData path
            APP_PATH=$(find ~/Library/Developer/Xcode/DerivedData -path "*Build/Products/Release-iphoneos/*.app" -print -quit)
          fi
          echo "APP_PATH=$APP_PATH"
          mkdir -p Payload
          cp -R "$APP_PATH" Payload/
          zip -r WiFiOffline-unsigned.ipa Payload
          rm -rf Payload

      - name: Upload unsigned IPA
        uses: actions/upload-artifact@v4
        with:
          name: WiFiOffline-unsigned
          path: WiFiOffline-unsigned.ipa
