name: build-unsigned-ipa-tuist

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show Xcode / macOS
        run: |
          xcodebuild -version
          sw_vers

      - name: Install Tuist
        run: |
          brew update
          brew tap tuist/tuist
          brew install --formula tuist
          tuist version

      - name: Normalize & validate Info.plist
        shell: bash
        run: |
          set -euo pipefail
          if [[ ! -f Info.plist ]]; then
            echo "❌ Missing Info.plist"; exit 1
          fi
          python3 - <<'PY'
from pathlib import Path
p = Path('Info.plist')
b = p.read_bytes()
if b.startswith(b'\xef\xbb\xbf'): b=b[3:]
b = b.replace(b'\r\n', b'\n').replace(b'\r', b'\n')
p.write_bytes(b)
PY
          plutil -convert xml1 Info.plist
          plutil -lint Info.plist

      - name: Generate Xcode project (Tuist)
        run: tuist generate --no-open

      - name: Detect workspace/project (once)
        id: where
        shell: bash
        run: |
          set -euo pipefail
          shopt -s nullglob
          workspaces=( ./*.xcworkspace )
          projects=( ./*.xcodeproj )
          if (( ${#workspaces[@]} > 0 )); then
            echo "type=workspace" >> $GITHUB_OUTPUT
            echo "path=${workspaces[0]}" >> $GITHUB_OUTPUT
            echo "Found workspace: ${workspaces[0]}"
          elif (( ${#projects[@]} > 0 )); then
            echo "type=project" >> $GITHUB_OUTPUT
            echo "path=${projects[0]}" >> $GITHUB_OUTPUT
            echo "Found project: ${projects[0]}"
          else
            echo "❌ No .xcworkspace or .xcodeproj" ; exit 1
          fi

      - name: Build unsigned .app (iphoneos)
        shell: bash
        run: |
          set -euo pipefail
          DERIVED="build"
          SCHEME="WiFiOffline"

          if [[ "${{ steps.where.outputs.type }}" == "workspace" ]]; then
            xcodebuild -workspace "${{ steps.where.outputs.path }}" \
              -scheme "$SCHEME" -configuration Release \
              -sdk iphoneos -destination 'generic/platform=iOS' \
              CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGNING_IDENTITY="" \
              -derivedDataPath "$DERIVED" clean build
          else
            xcodebuild -project "${{ steps.where.outputs.path }}" \
              -scheme "$SCHEME" -configuration Release \
              -sdk iphoneos -destination 'generic/platform=iOS' \
              CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGNING_IDENTITY="" \
              -derivedDataPath "$DERIVED" clean build
          fi

      - name: Package unsigned IPA (proper, with fallbacks)
        shell: bash
        run: |
          set -euo pipefail
          SCHEME="WiFiOffline"
          CONFIG="Release"

          # 1) Lấy APP_PATH từ showBuildSettings gắn với đúng ref (workspace/project)
          if [[ "${{ steps.where.outputs.type }}" == "workspace" ]]; then
            APP_PATH=$(xcodebuild -workspace "${{ steps.where.outputs.path }}" \
              -scheme "$SCHEME" -configuration "$CONFIG" -sdk iphoneos -showBuildSettings 2>/dev/null \
              | awk -F' = ' '
                  /TARGET_BUILD_DIR/ { t=$2 }
                  /WRAPPER_NAME/     { w=$2 }
                  END { if (t && w) print t "/" w }')
          else
            APP_PATH=$(xcodebuild -project "${{ steps.where.outputs.path }}" \
              -scheme "$SCHEME" -configuration "$CONFIG" -sdk iphoneos -showBuildSettings 2>/dev/null \
              | awk -F' = ' '
                  /TARGET_BUILD_DIR/ { t=$2 }
                  /WRAPPER_NAME/     { w=$2 }
                  END { if (t && w) print t "/" w }')
          fi

          # 2) Fallback: quét trong DerivedData build path
          if [[ -z "${APP_PATH:-}" || ! -d "$APP_PATH" ]]; then
            APP_PATH=$(find build/Build/Products/Release-iphoneos -maxdepth 1 -type d -name "*.app" -print -quit || true)
          fi

          echo "APP_PATH=$APP_PATH"
          if [[ -z "${APP_PATH:-}" || ! -d "$APP_PATH" ]]; then
            echo "❌ .app not found after build" ; find build -maxdepth 4 -type d -name "*.app" ; exit 1
          fi

          APP_NAME=$(basename "$APP_PATH" .app)

          echo "== Tree of built app =="
          /usr/bin/du -sh "$APP_PATH" || true
          /bin/ls -lah "$APP_PATH" | sed -n '1,120p'

          rm -rf Payload *.ipa
          mkdir -p Payload
          cp -R "$APP_PATH" "Payload/$APP_NAME.app"

          PLIST="Payload/$APP_NAME.app/Info.plist"
          echo "== Validate Info.plist in .app =="
          /usr/libexec/PlistBuddy -c 'Print :CFBundleIdentifier' "$PLIST"
          /usr/libexec/PlistBuddy -c 'Print :CFBundleExecutable' "$PLIST"
          /usr/libexec/PlistBuddy -c 'Print :CFBundleShortVersionString' "$PLIST" || true
          /usr/libexec/PlistBuddy -c 'Print :CFBundleVersion' "$PLIST" || true

          IPA_NAME="${APP_NAME}-unsigned.ipa"
          ditto -ck --sequesterRsrc --keepParent Payload "$IPA_NAME"

          echo "== IPA content preview =="
          unzip -l "$IPA_NAME" | sed -n '1,80p'
          ls -lah "$IPA_NAME"
          SIZE=$(stat -f%z "$IPA_NAME" || stat -c%s "$IPA_NAME")
          if (( SIZE < 500000 )); then
            echo "❌ IPA quá nhỏ ($SIZE bytes). Có gì đó sai ở bước build/packaging." ; exit 1
          fi

      - name: Upload artifact (unsigned IPA)
        uses: actions/upload-artifact@v4
        with:
          name: unsigned-ipa
          path: "*.ipa"
          if-no-files-found: error
