name: build-unsigned-ipa

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show repo tree
        run: |
          pwd
          ls -la
          echo "---- Sources ----"
          ls -la Sources || true
          echo "---- Entitlements ----"
          ls -la Entitlements || true
          echo "---- project.yml ----"
          cat project.yml

      - name: Install tools
        run: |
          brew update
          brew install xcodegen
          xcodebuild -version
          xcrun --sdk iphoneos --show-sdk-version

      - name: Generate Xcode project
        run: |
          xcodegen generate
          echo "Generated project files:"
          ls -la *.xcodeproj || echo "No .xcodeproj found"
          ls -la *.xcworkspace || echo "No .xcworkspace found"

      - name: Build unsigned .app (iphoneos)
        run: |
          set -euo pipefail
          xcodebuild -scheme "WiFiOffline" \
            -configuration Release \
            -sdk iphoneos \
            -destination 'generic/platform=iOS' \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_IDENTITY="" \
            -derivedDataPath build \
            build

      - name: Package IPA
        run: |
          set -euo pipefail
          echo "Looking for built app..."
          find build -name "*.app" -type d
          APP_PATH=$(find build -name "*.app" -type d -print -quit)
          if [ -z "$APP_PATH" ]; then
            echo "Error: No .app file found in build directory"
            exit 1
          fi
          echo "Found app at: $APP_PATH"
          mkdir -p Payload
          cp -R "$APP_PATH" Payload/
          /usr/bin/zip -qry WiFiOffline-unsigned.ipa Payload
          rm -rf Payload
          echo "IPA created: WiFiOffline-unsigned.ipa"
          ls -la WiFiOffline-unsigned.ipa

      - name: Upload unsigned IPA
        uses: actions/upload-artifact@v4
        with:
          name: WiFiOffline-unsigned
          path: WiFiOffline-unsigned.ipa
