name: build-unsigned-ipa-tuist

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Cài Tuist bằng formula để tránh cảnh báo cask
      - name: Install Tuist
        run: |
          brew update
          brew tap tuist/tuist
          brew install --formula tuist
          tuist version

      # (Không cần sinh Project.swift bằng here-doc nữa, vì đã commit sẵn trong repo)

      - name: Generate Xcode project (Tuist)
        run: tuist generate --no-open

      - name: Show Xcode / macOS
        run: |
          xcodebuild -version
          sw_vers

      # Build unsigned .app (iphoneos). Tự nhận workspace/project mà Tuist tạo.
      - name: Build unsigned .app (iphoneos)
        run: |
          set -euo pipefail
          DERIVED="build"
          SCHEME="WiFiOffline"

          if ls *.xcworkspace >/dev/null 2>&1; then
            WS=$(ls *.xcworkspace | head -n1)
            xcodebuild -workspace "$WS" \
              -scheme "$SCHEME" \
              -configuration Release \
              -sdk iphoneos \
              -destination 'generic/platform=iOS' \
              CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGNING_IDENTITY="" \
              -derivedDataPath "$DERIVED" \
              clean build
          else
            PROJ=$(ls *.xcodeproj | head -n1)
            xcodebuild -project "$PROJ" \
              -scheme "$SCHEME" \
              -configuration Release \
              -sdk iphoneos \
              -destination 'generic/platform=iOS' \
              CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGNING_IDENTITY="" \
              -derivedDataPath "$DERIVED" \
              clean build
          fi

      # Đóng gói .ipa unsigned từ sản phẩm build
      - name: Package unsigned IPA
        run: |
          set -euo pipefail
          PROD_DIR="build/Build/Products/Release-iphoneos"
          APP_PATH=$(find "$PROD_DIR" -maxdepth 1 -type d -name "*.app" -print -quit)
          if [ -z "${APP_PATH:-}" ]; then
            echo "Không tìm thấy .app ở $PROD_DIR"; ls -lah "$PROD_DIR" || true; exit 1
          fi
          APP_NAME=$(basename "$APP_PATH" .app)
          mkdir -p payload/Payload
          cp -R "$APP_PATH" "payload/Payload/$APP_NAME.app"
          (cd payload && zip -qry "../${APP_NAME}-unsigned.ipa" Payload)
          echo "IPA: ${APP_NAME}-unsigned.ipa"
          ls -lah "${APP_NAME}-unsigned.ipa"

      - name: Upload artifact (unsigned IPA)
        uses: actions/upload-artifact@v4
        with:
          name: unsigned-ipa
          path: "*.ipa"
          if-no-files-found: error
