name: build-unsigned-ipa-tuist

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show Xcode / macOS
        run: |
          xcodebuild -version
          sw_vers

      - name: Install Tuist
        run: |
          brew update
          brew tap tuist/tuist
          brew install --formula tuist
          tuist version

      # === FIX CRLF/BOM & validate Info.plist trước khi build ===
      - name: Normalize & validate Info.plist
        shell: bash
        run: |
          set -euo pipefail
          if [[ ! -f Info.plist ]]; then
            echo "❌ Missing Info.plist at repo root"; exit 1
          fi

          # Remove CRLF (Windows) -> LF, remove UTF-8 BOM nếu có
          python3 - <<'PY'
from pathlib import Path
p = Path('Info.plist')
raw = p.read_bytes()
# strip UTF-8 BOM nếu có
if raw.startswith(b'\xef\xbb\xbf'):
    raw = raw[3:]
# đổi CRLF -> LF
raw = raw.replace(b'\r\n', b'\n').replace(b'\r', b'\n')
p.write_bytes(raw)
PY

          # convert về xml1 và lint
          plutil -convert xml1 Info.plist || { echo "❌ convert failed"; cat Info.plist; exit 1; }
          plutil -lint Info.plist

      - name: Generate Xcode project (Tuist)
        run: tuist generate --no-open

      - name: Debug list after generate
        run: |
          set -euo pipefail
          pwd
          ls -lah
          find . -maxdepth 2 -type d -name "*.xcworkspace" -print
          find . -maxdepth 2 -type d -name "*.xcodeproj" -print

      - name: Build unsigned .app (iphoneos)
        shell: bash
        run: |
          set -euo pipefail
          DERIVED="build"
          SCHEME="WiFiOffline"

          shopt -s nullglob
          workspaces=( ./*.xcworkspace )
          projects=( ./*.xcodeproj )

          if (( ${#workspaces[@]} > 0 )); then
            xcodebuild -workspace "${workspaces[0]}" \
              -scheme "$SCHEME" \
              -configuration Release \
              -sdk iphoneos \
              -destination 'generic/platform=iOS' \
              CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGNING_IDENTITY="" \
              -derivedDataPath "$DERIVED" \
              clean build
          elif (( ${#projects[@]} > 0 )); then
            xcodebuild -project "${projects[0]}" \
              -scheme "$SCHEME" \
              -configuration Release \
              -sdk iphoneos \
              -destination 'generic/platform=iOS' \
              CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGNING_IDENTITY="" \
              -derivedDataPath "$DERIVED" \
              clean build
          else
            echo "❌ No .xcworkspace or .xcodeproj found"; exit 1
          fi

      # === Package IPA đúng chuẩn bằng ditto + verify Info.plist trong .app ===
      - name: Package unsigned IPA (proper)
        shell: bash
        run: |
          set -euo pipefail
          SCHEME="WiFiOffline"
          CONFIG="Release"

          APP_PATH=$(xcodebuild -showBuildSettings \
            -scheme "$SCHEME" -configuration "$CONFIG" -sdk iphoneos 2>/dev/null \
            | awk -F' = ' '
                /TARGET_BUILD_DIR/ { t=$2 }
                /WRAPPER_NAME/     { w=$2 }
                END { if (t && w) print t "/" w }' )

          [[ -z "${APP_PATH:-}" || ! -d "$APP_PATH" ]] && { echo "❌ .app not found"; exit 1; }
          APP_NAME=$(basename "$APP_PATH" .app)
          echo "✅ APP_PATH = $APP_PATH"

          rm -rf Payload *.ipa
          mkdir -p Payload
          cp -R "$APP_PATH" "Payload/$APP_NAME.app"

          PLIST="Payload/$APP_NAME.app/Info.plist"
          echo "== Info.plist in .app =="
          plutil -p "$PLIST" | head -n 50 || true
          echo "CFBundleIdentifier: $(/usr/libexec/PlistBuddy -c 'Print :CFBundleIdentifier' "$PLIST")"
          echo "CFBundleExecutable: $(/usr/libexec/PlistBuddy -c 'Print :CFBundleExecutable' "$PLIST")"

          IPA_NAME="${APP_NAME}-unsigned.ipa"
          ditto -ck --sequesterRsrc --keepParent Payload "$IPA_NAME"
          unzip -l "$IPA_NAME" | head -n 40
          ls -lah "$IPA_NAME"

      - name: Upload artifact (unsigned IPA)
        uses: actions/upload-artifact@v4
        with:
          name: unsigned-ipa
          path: "*.ipa"
          if-no-files-found: error
