name: iOS CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v3
      - name: Install Tuist
        run: brew install tuist@4.67.2
      - name: Generate Xcode project
        run: tuist generate --no-open
      - name: Build IPA unsigned
        run: |
          set -euo pipefail
          xcodebuild -workspace WiFiOffline.xcworkspace \
            -scheme WiFiOffline \
            -configuration Release \
            -sdk iphoneos \
            -destination generic/platform=iOS \
            CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_IDENTITY="" \
            -derivedDataPath build clean build
          APP_PATH=$(find build/Build/Products/Release-iphoneos -name "*.app" | head -n 1)
          mkdir Payload
          cp -R "$APP_PATH" Payload/
          ditto -ck --sequesterRsrc --keepParent Payload WiFiOffline-unsigned.ipa
      - uses: actions/upload-artifact@v3
        with:
          name: ipa
          path: WiFiOffline-unsigned.ipa
