name: CI (Tuist)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v4

      # Cài Tuist theo hướng dẫn chính thức
      - name: Install Tuist
        run: |
          brew tap tuist/tuist
          brew install --formula tuist
          tuist version

      - name: Generate Xcode project with Tuist
        run: tuist generate --no-open

      - name: Show Xcode / macOS
        run: |
          xcodebuild -version
          sw_vers

      - name: Build (no codesign)
        run: |
          set -euo pipefail
          # Lấy scheme trùng tên target (Tuist tạo sẵn)
          SCHEME="WiFiOffline"
          xcodebuild \
            -scheme "$SCHEME" \
            -configuration Debug \
            -sdk macosx \
            CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" \
            clean build | xcpretty || exit ${PIPESTATUS[0]}
